// @fracta/contract — the shape of everything that crosses the Frame/Vector
// boundary, and the only thing that crosses. Neither repo imports the other;
// both import this. See docs/frame-phase-1.2-1.3-brief.md Part A for the
// design rationale behind each field.
//
// Frame is downstream for identity (Vector mints linkId) and upstream for
// clinical output (Frame produces FbaOutcomeBundle). Participant identifying
// details never cross this boundary — only the opaque link.

export const CONTRACT_VERSION = '1.0' as const
export type ContractVersion = typeof CONTRACT_VERSION

// Source of truth for the FAST domain union — kept as a runtime array (not
// just a TS union) so both the package and its consumers can assert its
// arity at test time, per the brief's A5 requirement.
export const FAST_DOMAINS = ['attention', 'escape', 'tangible', 'automatic'] as const
export type FastDomain = (typeof FAST_DOMAINS)[number]

export const ESCALATION_PHASES = [
  'baseline',
  'early_warning',
  'escalation',
  'peak',
  'de_escalation',
  'recovery',
] as const
export type EscalationPhase = (typeof ESCALATION_PHASES)[number]

// ---------------------------------------------------------------------------
// A1 — Identity. The one rule that must not bend.
// ---------------------------------------------------------------------------

export interface ParticipantLink {
  contractVersion: ContractVersion
  linkId: string // UUID, minted by Vector, stored by Frame — never generated by Frame
  vectorParticipantRef?: string // Vector's own key, opaque to Frame
  displayLabel: string // initials or practitioner-chosen alias — never identifying details
}

// ---------------------------------------------------------------------------
// A2 — Vector -> Frame
// ---------------------------------------------------------------------------

export interface PlanCycle {
  planType: 'full' | 'interim' | null
  planStartDate: string | null
  validityMonths: 12 | 5 | null // full = 12, interim = 5
  expiresAt: string | null // computed from start + validity, not stored twice
}

export interface ParticipantContext {
  contractVersion: ContractVersion
  linkId: string
  displayLabel: string
  planCycle: PlanCycle | null
  knownBehaviourLabels: string[] // from Form 02 triage — seeds Frame's behaviour list, never auto-creates
  consentAttested: boolean
  consentAttestedAt: string | null
}

// ---------------------------------------------------------------------------
// A3 — Frame -> Vector
// ---------------------------------------------------------------------------

export interface FbaOutcomeBundle {
  contractVersion: ContractVersion
  linkId: string // shared header — all outcomes belong to one participant
  generatedAt: string // ISO
  generatedBy: string // practitioner name + role, for attribution — the one deliberate exception to A1
  sourceExportId: string // ties to an immutable DocumentationExport snapshot
  planCycleRef: Pick<PlanCycle, 'planType' | 'expiresAt'> | null // echoed back from ParticipantContext, unmodified
  outcomes: FbaOutcome[] // 1-4 typical; validator warns above 6, never hard-caps
}

export interface SummaryStatementSlots {
  routine: string | null
  antecedent: string | null
  behaviour: string
  consequence: string | null
  functionDirection: 'access' | 'avoid' | null
  settingEvent: string | null
}

export interface FbaOutcomeSummaryStatement {
  rendered: string // the plain-English sentence
  slots: SummaryStatementSlots // structured, so Form 07 can re-render its own way
  completeness: 'full' | 'partial' // partial = one or more slots null
}

export interface FbaOutcomeHypothesis {
  screenerResult: FastDomain[]
  episodePatternResult: FastDomain[]
  agreementStatus: 'match' | 'partial_match' | 'mismatch' | 'insufficient_data'
  computedConfidence: 'low' | 'moderate' | 'high'
  practitionerConfidence: 1 | 2 | 3 | 4 | 5 | 6 | null // separate, never merged into computedConfidence
  lastComputedAt: string
  caveat: string // mandatory EFA caveat, carried as data — required non-empty
}

export interface FbaOutcomeEvidenceBase {
  episodeCount: number
  distinctDayCount: number
  screenerCount: number
  episodeIds: string[] // audit trail crosses the boundary intact
  screenerIds: string[]
}

export type OpenRiskFlagStatus = 'open' | 'acknowledged' | 'escalated_to_efa'

export interface FbaOutcomeOpenRiskFlag {
  flagId: string
  triggerType: string
  triggeredAt: string
  status: OpenRiskFlagStatus
}

export interface FbaOutcomeBehaviour {
  label: string
  operationalDefinition: string // required, observable only — no interpretation
  status: 'active' | 'monitoring' | 'resolved'
}

export interface FbaOutcome {
  behaviourRef: string
  behaviour: FbaOutcomeBehaviour
  summaryStatement: FbaOutcomeSummaryStatement
  hypothesis: FbaOutcomeHypothesis
  evidenceBase: FbaOutcomeEvidenceBase
  escalationCycle: Record<EscalationPhase, string[]> | null // resolved display text, not item IDs
  openRiskFlags: FbaOutcomeOpenRiskFlag[]
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface ValidationResult {
  ok: boolean
  errors: string[]
  warnings: string[]
}

function ok(warnings: string[] = []): ValidationResult {
  return { ok: true, errors: [], warnings }
}

function fail(errors: string[], warnings: string[] = []): ValidationResult {
  return { ok: false, errors, warnings }
}

function isNonEmptyString(v: unknown): v is string {
  return typeof v === 'string' && v.trim().length > 0
}

export function validateParticipantLink(input: unknown): ValidationResult {
  const errors: string[] = []
  if (typeof input !== 'object' || input === null) return fail(['ParticipantLink must be an object.'])
  const link = input as Record<string, unknown>

  if (link.contractVersion !== CONTRACT_VERSION) {
    errors.push(`Unknown contractVersion: ${String(link.contractVersion)}. Expected "${CONTRACT_VERSION}".`)
  }
  if (!isNonEmptyString(link.linkId)) errors.push('linkId is required and must be a non-empty string.')
  if (!isNonEmptyString(link.displayLabel)) errors.push('displayLabel is required and must be a non-empty string.')

  return errors.length ? fail(errors) : ok()
}

export function validateParticipantContext(input: unknown): ValidationResult {
  const errors: string[] = []
  if (typeof input !== 'object' || input === null) return fail(['ParticipantContext must be an object.'])
  const ctx = input as Record<string, unknown>

  if (ctx.contractVersion !== CONTRACT_VERSION) {
    errors.push(`Unknown contractVersion: ${String(ctx.contractVersion)}. Expected "${CONTRACT_VERSION}".`)
  }
  if (!isNonEmptyString(ctx.linkId)) errors.push('linkId is required and must be a non-empty string.')
  if (!isNonEmptyString(ctx.displayLabel)) errors.push('displayLabel is required and must be a non-empty string.')
  if (!Array.isArray(ctx.knownBehaviourLabels)) {
    errors.push('knownBehaviourLabels must be an array.')
  }
  if (typeof ctx.consentAttested !== 'boolean') errors.push('consentAttested must be a boolean.')

  return errors.length ? fail(errors) : ok()
}

function validateSummaryStatement(s: unknown, index: number): string[] {
  const errors: string[] = []
  const prefix = `outcomes[${index}].summaryStatement`
  if (typeof s !== 'object' || s === null) return [`${prefix} must be an object.`]
  const statement = s as Record<string, unknown>
  if (!isNonEmptyString(statement.rendered)) errors.push(`${prefix}.rendered is required.`)
  if (statement.completeness !== 'full' && statement.completeness !== 'partial') {
    errors.push(`${prefix}.completeness must be "full" or "partial".`)
  }
  if (typeof statement.slots !== 'object' || statement.slots === null) {
    errors.push(`${prefix}.slots is required.`)
  } else if (!isNonEmptyString((statement.slots as Record<string, unknown>).behaviour)) {
    errors.push(`${prefix}.slots.behaviour is required.`)
  }
  return errors
}

function validateHypothesis(h: unknown, index: number): string[] {
  const errors: string[] = []
  const prefix = `outcomes[${index}].hypothesis`
  if (typeof h !== 'object' || h === null) return [`${prefix} must be an object.`]
  const hyp = h as Record<string, unknown>

  if (!isNonEmptyString(hyp.caveat)) {
    errors.push(`${prefix}.caveat is required and must not be empty or whitespace.`)
  }
  if (!Array.isArray(hyp.screenerResult) || hyp.screenerResult.some((d) => !FAST_DOMAINS.includes(d))) {
    errors.push(`${prefix}.screenerResult must be an array of valid FastDomain values.`)
  }
  if (!Array.isArray(hyp.episodePatternResult) || hyp.episodePatternResult.some((d) => !FAST_DOMAINS.includes(d))) {
    errors.push(`${prefix}.episodePatternResult must be an array of valid FastDomain values.`)
  }
  if (hyp.practitionerConfidence !== null && !(Number(hyp.practitionerConfidence) >= 1 && Number(hyp.practitionerConfidence) <= 6)) {
    errors.push(`${prefix}.practitionerConfidence must be 1-6 or null.`)
  }

  return errors
}

function validateEvidenceBase(e: unknown, index: number): string[] {
  const errors: string[] = []
  const prefix = `outcomes[${index}].evidenceBase`
  if (typeof e !== 'object' || e === null) return [`${prefix} must be an object.`]
  const evidence = e as Record<string, unknown>
  if (!Array.isArray(evidence.episodeIds)) errors.push(`${prefix}.episodeIds must be an array.`)
  if (!Array.isArray(evidence.screenerIds)) errors.push(`${prefix}.screenerIds must be an array.`)
  return errors
}

function validateOutcome(input: unknown, index: number): string[] {
  const errors: string[] = []
  if (typeof input !== 'object' || input === null) return [`outcomes[${index}] must be an object.`]
  const outcome = input as Record<string, unknown>

  if (!isNonEmptyString(outcome.behaviourRef)) errors.push(`outcomes[${index}].behaviourRef is required.`)

  const behaviour = outcome.behaviour as Record<string, unknown> | undefined
  if (typeof behaviour !== 'object' || behaviour === null) {
    errors.push(`outcomes[${index}].behaviour must be an object.`)
  } else {
    if (!isNonEmptyString(behaviour.operationalDefinition)) {
      errors.push(`outcomes[${index}].behaviour.operationalDefinition is required and must not be empty.`)
    }
    if (!isNonEmptyString(behaviour.label)) errors.push(`outcomes[${index}].behaviour.label is required.`)
  }

  errors.push(...validateSummaryStatement(outcome.summaryStatement, index))
  errors.push(...validateHypothesis(outcome.hypothesis, index))
  errors.push(...validateEvidenceBase(outcome.evidenceBase, index))

  if (outcome.escalationCycle !== null && typeof outcome.escalationCycle !== 'object') {
    errors.push(`outcomes[${index}].escalationCycle must be an object or null.`)
  }
  if (!Array.isArray(outcome.openRiskFlags)) errors.push(`outcomes[${index}].openRiskFlags must be an array.`)

  return errors
}

const OUTCOME_COUNT_WARNING_THRESHOLD = 6

export function validateFbaOutcomeBundle(input: unknown): ValidationResult {
  const errors: string[] = []
  const warnings: string[] = []
  if (typeof input !== 'object' || input === null) return fail(['FbaOutcomeBundle must be an object.'])
  const bundle = input as Record<string, unknown>

  if (bundle.contractVersion !== CONTRACT_VERSION) {
    errors.push(`Unknown contractVersion: ${String(bundle.contractVersion)}. Expected "${CONTRACT_VERSION}".`)
  }
  // No minting fallback: a bundle with no linkId is invalid, full stop.
  if (!isNonEmptyString(bundle.linkId)) errors.push('linkId is required — a bundle cannot be generated without it.')
  if (!isNonEmptyString(bundle.generatedAt)) errors.push('generatedAt is required.')
  if (!isNonEmptyString(bundle.generatedBy)) errors.push('generatedBy is required.')
  if (!isNonEmptyString(bundle.sourceExportId)) errors.push('sourceExportId is required.')

  if (!Array.isArray(bundle.outcomes)) {
    errors.push('outcomes must be an array.')
  } else {
    if (bundle.outcomes.length === 0) {
      errors.push('outcomes must contain at least one FbaOutcome.')
    }
    if (bundle.outcomes.length > OUTCOME_COUNT_WARNING_THRESHOLD) {
      warnings.push(
        `Bundle contains ${bundle.outcomes.length} outcomes — typical plans cover 1-4. This is not blocked, but check it's intentional.`,
      )
    }
    bundle.outcomes.forEach((outcome, i) => errors.push(...validateOutcome(outcome, i)))
  }

  return errors.length ? fail(errors, warnings) : ok(warnings)
}

// ---------------------------------------------------------------------------
// PII denylist — enforced at test time via a fuzz test over serialised
// output, kept here so both the package's own tests and consumers can reuse
// the same list.
// ---------------------------------------------------------------------------

export const PII_KEY_DENYLIST = [
  'name',
  'firstName',
  'surname',
  'dob',
  'dateOfBirth',
  'ndisNumber',
  'address',
  'phone',
  'email',
] as const

export const PII_DENYLIST_ALLOWED_EXCEPTIONS = ['generatedBy'] as const

// Walks parsed JSON (object/array/primitive) and returns every object key
// found anywhere in the structure that matches PII_KEY_DENYLIST, excluding
// PII_DENYLIST_ALLOWED_EXCEPTIONS. Reusable by both this package's own fuzz
// test and by Frame's export path, which can run this defensively over a
// bundle immediately before emit.
export function findDenylistedKeys(value: unknown): string[] {
  const denylist = new Set<string>(PII_KEY_DENYLIST)
  const allowed = new Set<string>(PII_DENYLIST_ALLOWED_EXCEPTIONS)
  const found = new Set<string>()

  function walk(v: unknown) {
    if (Array.isArray(v)) {
      for (const item of v) walk(item)
      return
    }
    if (typeof v === 'object' && v !== null) {
      for (const [key, val] of Object.entries(v)) {
        if (denylist.has(key) && !allowed.has(key)) found.add(key)
        walk(val)
      }
    }
  }

  walk(value)
  return [...found]
}
